apiVersion: batch/v1
kind: CronJob

metadata:
  name: blablascan

spec:
  schedule: "* */6 * * *"
  jobTemplate:
    spec:
      backoffLimit: 5
      completions: 1
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: blablascan
            imagePullPolicy: Always
            image: dimage1/blablascan:2505
            envFrom:
            - secretRef:
                name: mongo-w-url
            - secretRef:
                name: blabla-api-secret
            args: ["Annecy", "basel,mulhouse,nice,avignon,marseille,turin,milan,bern,lausanne"]
