apiVersion: batch/v1
kind: Job

metadata:
  name: blablascan-job

spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: blablascan
        image: dimage1/blablascan:latest
        envFrom:
        - secretRef:
            name: mongo-w-url
        - secretRef:
            name: blabla-api-secret
        command: ["python3", "blablascan.py"]
        args: ["Annecy", "Mulhouse"]
