apiVersion: v1
kind: Pod
metadata:
  name: blablaweb
  labels:
    run: blablaweb
spec:
  containers:
  - name: blablaweb
    imagePullPolicy: Always
    image: dimage1/blablaweb:latest
    envFrom:
    - secretRef:
        name: mongo-w-url
    ports:
    - containerPort: 8080
---
#k expose pod blablaweb --name blablaweb --port=81 --target-port=8080 --type=LoadBalancer 
apiVersion: v1
kind: Service
metadata:
  labels:
    run: blablaweb
  name: blablaweb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    run: blablaweb
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 34.23.85.62

